# Generated by Django 4.2.30 on 2026-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('S0', 'S0-致命'), ('S1', 'S1-严重'), ('S2', 'S2-一般'), ('S3', 'S3-轻微'), ('S4', 'S4-建议')], db_index=True, default='S2', max_length=10),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('open', '未处理'), ('in_progress', '处理中'), ('resolved', '已修复'), ('closed', '已关闭')], db_index=True, default='open', max_length=20),
        ),
    ]
