# Generated by Django 6.0.6 on 2026-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_alter_defect_severity_alter_defect_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defect',
            options={},
        ),
    ]
