# Generated by Django 6.0.4 on 2026-05-18 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('P0', 'P0-最高'), ('P1', 'P1-高'), ('P2', 'P2-中'), ('P3', 'P3-低'), ('P4', 'P4-最低')], default='P2', max_length=10)),
                ('type', models.CharField(choices=[('functional', '功能测试'), ('api', '接口测试'), ('ui', 'UI测试'), ('performance', '性能测试')], default='functional', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('deprecated', '已废弃')], default='draft', max_length=20)),
                ('preconditions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testcases', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='projects.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='projects.project')),
            ],
            options={
                'db_table': 'test_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('action', models.TextField()),
                ('expected_result', models.TextField()),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='testcases.testcase')),
            ],
            options={
                'db_table': 'test_case_step',
                'ordering': ['step_number'],
            },
        ),
    ]
