# Generated by Django 4.2.30 on 2026-05-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='product_line',
            field=models.CharField(choices=[('camera', '摄像头'), ('doorbell', '门铃')], default='camera', max_length=20),
        ),
    ]
