# Generated by Django 4.2.30 on 2026-05-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0002_testcase_product_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='projects.project'),
        ),
    ]
