# Generated by Django 4.2.30 on 2026-05-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_alter_testcase_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testcasestep',
            name='expected_result',
            field=models.TextField(blank=True, default=''),
        ),
    ]
