# Generated by Django 4.2.30 on 2026-05-18 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testcases', '0004_alter_testcasestep_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_testcases', to=settings.AUTH_USER_MODEL),
        ),
    ]
