# Generated by Django 4.2.30 on 2026-05-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_testcase_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='priority',
            field=models.CharField(choices=[('P0', 'P0-最高'), ('P1', 'P1-高'), ('P2', 'P2-中'), ('P3', 'P3-低'), ('P4', 'P4-最低')], db_index=True, default='P2', max_length=10),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='product_line',
            field=models.CharField(choices=[('camera', '摄像头'), ('doorbell', '门铃')], db_index=True, default='camera', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '活跃'), ('deprecated', '已废弃')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('functional', '功能测试'), ('api', '接口测试'), ('ui', 'UI测试'), ('performance', '性能测试')], db_index=True, default='functional', max_length=20),
        ),
    ]
