# Generated by Django 6.0.6 on 2026-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_alter_testcase_priority_alter_testcase_product_line_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
    ]
