# Generated by Django 6.0.6 on 2026-07-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_alter_testcase_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='type',
            new_name='case_type',
        ),
    ]
