# Generated by Django 6.0.6 on 2026-07-17 06:43
# M11 fix: pg_trgm 索引是 PostgreSQL-specific，依赖 extension。
# 单元测试 / SQLite 不支持；用 RunSQL 包一层 + IF NOT EXISTS + catch IF EXISTS 扩展检查。
import django.contrib.postgres.indexes  # noqa
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_project_product_line'),
        ('testcases', '0008_rename_type_testcase_case_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcasestep',
            options={},
        ),
        # pg_trgm trigram 索引：仅在 PG 上 + extension 存在时创建；其它 DB 跳过。
        # TestCase.title__icontains 会自动走 trigram 索引，没有也能用（只是慢）。
        migrations.RunSQL(
            sql=(
                "CREATE EXTENSION IF NOT EXISTS pg_trgm;\n"
                "CREATE INDEX IF NOT EXISTS testcase_title_trgm_idx "
                "ON test_case USING gin (title gin_trgm_ops);"
            ),
            reverse_sql="DROP INDEX IF EXISTS testcase_title_trgm_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name='testcase',
                    index=models.Index(fields=['title'], name='testcase_title_trgm_idx', opclasses=['gin_trgm_ops']),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='testcasestep',
            index=models.Index(fields=['test_case', 'step_number'], name='test_case_s_test_ca_be9431_idx'),
        ),
    ]
