# Generated by Django 4.2.30 on 2026-05-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projecttask_testcaseassignment_projectmember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcaseassignment',
            unique_together=set(),
        ),
    ]
