# Generated by Django 4.2.30 on 2026-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_testcaseassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseassignment',
            name='approval_status',
            field=models.CharField(choices=[('pending', '未审核'), ('approved', '审核通过'), ('rejected', '审核不通过')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcaseassignment',
            name='status',
            field=models.CharField(choices=[('pending', '待测试'), ('in_progress', '测试中'), ('passed', 'Pass'), ('failed', 'Fail'), ('not_applicable', 'N/A'), ('not_tested', 'N/T')], default='pending', max_length=20),
        ),
    ]
