# Generated by Django 4.2.30 on 2026-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_testcaseassignment_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseassignment',
            name='status',
            field=models.CharField(choices=[('pending', '待测试'), ('passed', 'Pass'), ('failed', 'Fail'), ('not_applicable', 'N/A'), ('not_tested', 'N/T')], default='pending', max_length=20),
        ),
    ]
