# Generated by Django 4.2.30 on 2026-05-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_testcaseassignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_line',
            field=models.CharField(choices=[('camera', '摄像头'), ('doorbell', '门铃')], default='camera', max_length=20),
        ),
    ]
