# Generated by Django 4.2.30 on 2026-05-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0010_assignmentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='round',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='提测轮次'),
        ),
        migrations.AddField(
            model_name='testcaseassignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to='projects.projecttask', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='assignmentattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assignment_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
