# Generated by Django 6.0.6 on 2026-07-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projecttask_testcaseassignment_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projecttask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testcaseassignment',
            options={},
        ),
    ]
