# Generated by Django 6.0.6 on 2026-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projectmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('archived', '已归档')], db_index=True, default='active', max_length=20),
        ),
    ]
