# Generated by Django 6.0.6 on 2026-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='product_line',
            field=models.CharField(choices=[('camera', '摄像头'), ('doorbell', '门铃')], db_index=True, default='camera', max_length=20),
        ),
    ]
