# Generated by Django 6.0.6 on 2026-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testplan',
            options={},
        ),
    ]
