# Generated by Django 6.0.6 on 2026-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0002_alter_testplan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '执行中'), ('completed', '已完成')], db_index=True, default='draft', max_length=20),
        ),
    ]
