# Generated by Django 6.0.6 on 2026-07-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_alter_testcasestep_options_and_more'),
        ('testplans', '0003_alter_testplan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testplancase',
            options={},
        ),
        migrations.AddIndex(
            model_name='testplancase',
            index=models.Index(fields=['test_plan', 'order'], name='test_plan_c_test_pl_13d82d_idx'),
        ),
    ]
