# Generated by Django 4.2.30 on 2026-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('pass', '通过'), ('fail', '失败'), ('blocked', '阻塞'), ('skip', '跳过')], db_index=True, default='pending', max_length=20),
        ),
    ]
