# Generated by Django 6.0.6 on 2026-07-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0002_alter_testresult_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={},
        ),
    ]
