# Generated by Django 6.0.6 on 2026-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testruns', '0003_alter_testrun_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrun',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成')], db_index=True, default='pending', max_length=20),
        ),
    ]
