# Generated by Django 6.0.6 on 2026-07-17 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0007_alter_testcase_options'),
        ('testruns', '0004_alter_testrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='testresult',
            constraint=models.UniqueConstraint(fields=('test_run', 'test_case'), name='unique_test_run_case'),
        ),
    ]
