# Generated by Django 6.0.6 on 2026-07-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_verificationcode_purpose_hash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='verificationcode',
            new_name='verificatio_email_dd1952_idx',
            old_name='verification_email_purpose__idx',
        ),
    ]
