# Generated by Django 6.0.6 on 2026-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_verification_email_purpose__idx_verificatio_email_dd1952_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_my_projects',
            field=models.BooleanField(default=False, verbose_name='我的项目'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_projects',
            field=models.BooleanField(default=False, verbose_name='项目管理'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_testcase_library',
            field=models.BooleanField(default=False, verbose_name='测试用例库'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_manage_testcase_library',
            field=models.BooleanField(default=False, verbose_name='管理用例库'),
        ),
    ]
